/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.AlunoController;
import controllers.AtividadeController;
import controllers.InstrutorController;
import controllers.TreinoController;
import javax.swing.table.DefaultTableModel;
import model.Aluno;
import model.Atividade;
import model.Instrutor;
import model.Treino;
import model.Usuario;

/**
 *
 * @author vinic
 */
public class frmPrincipal extends javax.swing.JFrame {

    private Usuario user = new Usuario();
    private DefaultTableModel modelo = new DefaultTableModel();
    
    public frmPrincipal() {
        initComponents();
    }
    
    public frmPrincipal(Usuario usuario) {
        initComponents();
        user = usuario;
        lblTituloTabela.setVisible(false);
        lblUsuario.setText(user.getNome_usuario());
        if(usuario.getTipo_usuario().getLabel().equals("Instrutor")){
            menuCadastrarInstrutor.setEnabled(false);
        }
        if(usuario.getTipo_usuario().getLabel().equals("Aluno")){
            menuCadastrar.setEnabled(false);
            menuExibir.setEnabled(false);
            areaInstrutor.setEnabled(false);
        }
    }
    
    private void modelarTabelaAluno(){
        modelo.setColumnCount(0);
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("INSTRUTOR");
        tblPrincipal.setModel(modelo);
    }
    
    private void modelarTabelaInstrutor(){
        modelo.setNumRows(0);
        modelo.setColumnCount(0);
        modelo.addColumn("NOME");
        modelo.addColumn("CPF");
        modelo.addColumn("RG");
        modelo.addColumn("CTPS");
        modelo.addColumn("CARGA HORÁRIA");
        modelo.addColumn("QTD. ALUNOS");
        tblPrincipal.setModel(modelo);
    }
    
    private void modelarTabelaTreino(){
        modelo.setColumnCount(0);
        modelo.setColumnCount(0);
        modelo.addColumn("NOME");
        tblPrincipal.setModel(modelo);
    }
    
    private void modelarTabelaAtividade(){
        modelo.setColumnCount(0);
        modelo.addColumn("NOME");
        modelo.addColumn("NUMERO REPETIÇÕES");
        modelo.addColumn("PESO/TEMPO");
        tblPrincipal.setModel(modelo);
    }
    
    private void preencherTabelaAluno(){
        modelo.setNumRows(0);
        for(Aluno a: new AlunoController().Listar()){
            modelo.addRow(new Object[]{
                a.getNome(),
                a.getCpf(),
                a.getRg(),
                a.getInstrutor().getNome() 
            });
        }
    }
    
    private void preencherTabelaInstrutor(){
        modelo.setNumRows(0);
        for(Instrutor i: new InstrutorController().Listar()){
            modelo.addRow(new Object[]{
                i.getNome(),
                i.getCpf(),
                i.getRg(),
                i.getCtps(),
                i.getCargaHoraria(),
                i.getAlunos().size()
            });
        }
    }
    
    private void preencherTabelaTreino(){
        modelo.setNumRows(0);
        for(Treino t: new TreinoController().Listar()){
            modelo.addRow(new Object[]{
                t.getNome()
            });
        }
    }
    
    private void preencherTabelaAtividade(){
        modelo.setNumRows(0);
        for(Atividade atv: new AtividadeController().Listar()){
            modelo.addRow(new Object[]{
                atv.getNome(),
                atv.getNumeroRepeticoes(),
                atv.getPeso_tempo()         
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrincipal = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblTituloTabela = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuExibir = new javax.swing.JMenu();
        AlunosMatriculados = new javax.swing.JMenuItem();
        Instrutores = new javax.swing.JMenuItem();
        Treinos = new javax.swing.JMenuItem();
        Atividades = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuCadastrarInstrutor = new javax.swing.JMenuItem();
        menuCadastrarAluno = new javax.swing.JMenuItem();
        menuCadastrarAtividadeFisica = new javax.swing.JMenuItem();
        menuCadastrarTreino = new javax.swing.JMenuItem();
        areaAluno = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        areaInstrutor = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuOpcoesSair = new javax.swing.JMenuItem();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tblPrincipal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPrincipal);

        jLabel3.setText("BEM-VINDO");

        lblUsuario.setText("@usuario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(58, 58, 58))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(49, 49, 49))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTituloTabela.setBackground(new java.awt.Color(0, 0, 0));
        lblTituloTabela.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTituloTabela.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(lblTituloTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(252, 252, 252))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblTituloTabela)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuExibir.setText("Exibir");

        AlunosMatriculados.setText("Alunos Matriculados");
        AlunosMatriculados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlunosMatriculadosActionPerformed(evt);
            }
        });
        menuExibir.add(AlunosMatriculados);

        Instrutores.setText("Instrutores");
        Instrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InstrutoresActionPerformed(evt);
            }
        });
        menuExibir.add(Instrutores);

        Treinos.setText("Treinos");
        Treinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TreinosActionPerformed(evt);
            }
        });
        menuExibir.add(Treinos);

        Atividades.setText("Atividades ");
        Atividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtividadesActionPerformed(evt);
            }
        });
        menuExibir.add(Atividades);

        jMenuBar1.add(menuExibir);

        menuCadastrar.setText("Cadastrar");

        menuCadastrarInstrutor.setText("Instrutor");
        menuCadastrarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarInstrutorActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarInstrutor);

        menuCadastrarAluno.setText("Aluno");
        menuCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAlunoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAluno);

        menuCadastrarAtividadeFisica.setText("Atividade Física");
        menuCadastrarAtividadeFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarAtividadeFisicaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarAtividadeFisica);

        menuCadastrarTreino.setText("Treino");
        menuCadastrarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarTreinoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuCadastrarTreino);

        jMenuBar1.add(menuCadastrar);

        areaAluno.setText("Area Aluno");

        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        areaAluno.add(jMenuItem2);

        jMenuBar1.add(areaAluno);

        areaInstrutor.setText("Area Instrutor");

        jMenuItem6.setText("Abrir");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        areaInstrutor.add(jMenuItem6);

        jMenuBar1.add(areaInstrutor);

        jMenu2.setText("Opções");

        menuOpcoesSair.setText("Sair");
        menuOpcoesSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcoesSairActionPerformed(evt);
            }
        });
        jMenu2.add(menuOpcoesSair);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlunosMatriculadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlunosMatriculadosActionPerformed
        modelarTabelaAluno();
        preencherTabelaAluno();
        lblTituloTabela.setText("ALUNOS MATRICULADOS");
        lblTituloTabela.setVisible(true);
    }//GEN-LAST:event_AlunosMatriculadosActionPerformed

    private void InstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InstrutoresActionPerformed
        modelarTabelaInstrutor();
        preencherTabelaInstrutor();
        lblTituloTabela.setText("INSTRUTORES");
        lblTituloTabela.setVisible(true);
    }//GEN-LAST:event_InstrutoresActionPerformed

    private void TreinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TreinosActionPerformed
        modelarTabelaTreino();
        preencherTabelaTreino();
        lblTituloTabela.setText("TREINOS");
        lblTituloTabela.setVisible(true);
    }//GEN-LAST:event_TreinosActionPerformed

    private void AtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtividadesActionPerformed
        modelarTabelaAtividade();
        preencherTabelaAtividade();
        lblTituloTabela.setText("ATIVIDADES");
        lblTituloTabela.setVisible(true);
    }//GEN-LAST:event_AtividadesActionPerformed

    private void menuOpcoesSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcoesSairActionPerformed
        this.dispose();
        new frmLogin().setVisible(true);
    }//GEN-LAST:event_menuOpcoesSairActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new frmAluno().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAlunoActionPerformed
        new frmAlunoCadastro().setVisible(true);
    }//GEN-LAST:event_menuCadastrarAlunoActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        new frmInstrutor(user).setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuCadastrarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarInstrutorActionPerformed
        new frmInstrutorCadastro().setVisible(true);
    }//GEN-LAST:event_menuCadastrarInstrutorActionPerformed

    private void menuCadastrarAtividadeFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarAtividadeFisicaActionPerformed
        new frmAtividadeCadastro().setVisible(true);
    }//GEN-LAST:event_menuCadastrarAtividadeFisicaActionPerformed

    private void menuCadastrarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarTreinoActionPerformed
        new frmTreinoCadastro().setVisible(true);
    }//GEN-LAST:event_menuCadastrarTreinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AlunosMatriculados;
    private javax.swing.JMenuItem Atividades;
    private javax.swing.JMenuItem Instrutores;
    private javax.swing.JMenuItem Treinos;
    private javax.swing.JMenu areaAluno;
    private javax.swing.JMenu areaInstrutor;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTituloTabela;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuCadastrarAluno;
    private javax.swing.JMenuItem menuCadastrarAtividadeFisica;
    private javax.swing.JMenuItem menuCadastrarInstrutor;
    private javax.swing.JMenuItem menuCadastrarTreino;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JMenuItem menuOpcoesSair;
    private javax.swing.JTable tblPrincipal;
    // End of variables declaration//GEN-END:variables
}
